# Generated by Django 4.0.3 on 2024-01-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=10)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('advId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adApp.adv')),
            ],
        ),
    ]
