# Generated by Django 5.0.1 on 2024-01-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAnlz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('num_of_shows', models.IntegerField(default=0)),
                ('total_revenue', models.IntegerField(default=0)),
                ('num_of_redirects', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('previews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.IntegerField(default=0)),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='advId',
            new_name='adv_id',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adv',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adv',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adv',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
