# Generated by Django 5.0.1 on 2024-01-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0002_adanlz_user_rename_advid_ad_adv_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='ad_price',
            new_name='price',
        ),
    ]
