# Generated by Django 5.0.1 on 2024-01-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0003_rename_ad_price_ad_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='price',
            new_name='ad_price',
        ),
    ]
