# Generated by Django 5.0.1 on 2024-01-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0005_mediatest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mediatest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mediatest',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
