# Generated by Django 5.0.1 on 2024-01-18 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0006_alter_ad_end_time_alter_ad_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ad')),
                ('desc', models.CharField(blank=True, max_length=20)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adApp.ad')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaTest',
        ),
    ]
