# Generated by Django 5.0.1 on 2024-01-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0008_ad_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='target_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_gender',
            field=models.CharField(choices=[('남', '남성'), ('여', '여성'), ('없음', '없음')], default='없음', max_length=2),
        ),
    ]
