# Generated by Django 5.0.1 on 2024-01-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0009_ad_target_age_ad_target_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='target_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adv',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='desc',
            field=models.CharField(max_length=20),
        ),
    ]
