# Generated by Django 5.0.1 on 2024-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0010_alter_ad_ad_price_alter_ad_target_age_alter_ad_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='adv_id',
        ),
        migrations.AddField(
            model_name='ad',
            name='adv_name',
            field=models.CharField(default='회사명', max_length=10),
        ),
    ]
