# Generated by Django 5.0.1 on 2024-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0011_remove_ad_adv_id_ad_adv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='adv_name',
            field=models.CharField(max_length=10),
        ),
    ]
