# Generated by Django 5.0.1 on 2024-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adApp', '0013_alter_adv_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdAnlz',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='ad',
            name='target_age',
            field=models.IntegerField(default=0),
        ),
    ]
